### ISSUE TITLE
[Feature request]: Improve files and folder exclusion

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#275]
### Whats the feature you would like to be added?

to be able to exclude folders would be a plus. Such as those cache folders found in the mods directory, and some config folders that some client mods add that are just too large to be on a server, fancymenu.

that would alleviate the need to figure out what mods are creating which config folders as then it would be on the pack dev to exclude them.

### Anything else you would like to add?

if you have a mod pack, you need to add BH-MENU to it. :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya Kreezxil,

thanks for opening this feature request.

This feature is already partially implemented, as you've probably already seen in the README or help section in ServerPackCreator itself.

However, there is room for improvement, especially in the mods-directory. The exclusion was initially implemented with a focus in files/folders in directories like `config`.

If I recall correctly, you've already used it with Fancymenu in the past.

The improvements will land in 3.x and won't make it into release of 3.0.0. No ETA though. 🙂

Cheers,
Griefed

**Comment by kreezxil** [comment]
I was asking for a line where I can input folders to be ignored. Another
option would be to have SPC parse for a filename called “.ignore_me” that
we devs could put in folders to be ignored. So that folder and any child
folders would be ignored. I sense that you want me to read the README.
That's too easy, but I'll give it a whirl.

**Comment by Griefed** [comment]
> I was asking for a line where I can input folders to be ignored. 

As I said, that already eyists, albeit partially. It needs improvdments for the mods-directory, but exclusion of files and folders has been possible for quite some time now. :)

**Comment by Griefed** [comment]
> I was asking for a line where I can input folders to be ignored. 

As I said, that already eyists, albeit partially. It needs improvdments for the mods-directory to fit the needs you specified, as it doesn't all zo great when excluding folders in the mods-directory. In essence, though, exclusion of files and folders has been possible for quite some time now.

I'll make it a priority for 3.x. :)

**Comment by Griefed** [comment]
Heya Kreezxil,

good news. I've just implemented the changes to exlclude files and folders from the mods-directory, so they will be available in the next version. 😊

Cheers,
Griefed

**Comment by kreezxil** [comment]
> Heya Kreezxil,
> 
> good news. I've just implemented the changes to exclude files and folders from the mods-directory, so they will be available in the next version. blush
> 
> Cheers, Griefed

Can you explain that better, not sure if you implemented the idea the way I had envisioned it, or simply finished your vision of it.

**Comment by Griefed** [comment]
I finished/improved the already existing possibility of ignoring files and/or folders.

If you want to exclude something, you prefix an entry in your `copyDirs` or `Enter the list of directories or files in your modpack to include in the server pack:` in the GUI with an `!`

like so:
- `!config/fancymenu`
- `!config/CustomMainMenu`
- `!config/clienttweaks-client.toml`

Now, previously, when you added an entry like `!mods/some_folder/` or `!mods/cache/some_file.txt` these would not have been excluded because the exclusion was more focused on any other folder/file other than mods. SPC already had the clientside-only mods list and automatic sideness scanning.

**Now** if you specify `!mods/cache` or `!mods/cache/some_file.txt` or `!mods/cache/some_jar.jar` they will actually be excluded. **That** did not work previously.

Maybe the GUI and config will receive an extra field for exclusions in the rework at some point. It's a lot of work for little benefit to split file/folders to include from files/folders to exclude in my opinion.

> Another option would be to have SPC parse for a filename called “.ignore_me” that we devs could put in folders to be ignored.

You'll need to explain this one in greater detail to me. How would you expect this to work? Where would this file be stored? Why would a modpack-specific exclusion be separated from a serverpackcreator.conf which is already modpack-specific?

Or do you envision something along the lines of [this feature?](https://git.griefed.de/Griefed/ServerPackCreator/-/issues/135)

**Comment by Griefed** [comment]
There's a small(ish) wiki article containing some help now as well: https://wiki.griefed.de/en/Documentation/ServerPackCreator/ServerPackCreator-Help

It's a bit easier to navigate than the README or the current help window in SPC. The help window will be replace with a button which leads you to the above mentioned wiki article, in a future version Soon™ to be released. 🙂

**Comment by Griefed** [comment]
Exclusion fixed as of version [3.1.0](https://github.com/Griefed/ServerPackCreator/releases/tag/3.1.0).

For details as to how the exclusion of files and folders works, please take a look at the aforementioned [wiki article](https://wiki.griefed.de/en/Documentation/ServerPackCreator/ServerPackCreator-Help#excluding-filesfolders)

Cheers,
Griefed
