### ISSUE TITLE
appLogger.debug() messages doesn't appear in logs

### ISSUE THREAD

**Issue by whitebear60** [Griefed/ServerPackCreator#28]

**Comment by Griefed** [comment]
Intended. Meant to be switched on by experienced users by editing the log4j2.xml in the jar file, or by devs in their dev environment. Setting this to info or adding it to regular logging would inflate the log file and make previous endeavoures to make it readable void.
In order to activate debug logging in the log file, one would have to:
1. Extract the `log4j2.xml` from the jar file to any location
2. Change 
```
            <AppenderRef ref="Console" level="info"/>
            <AppenderRef ref="ApplicationLogger" level="info" />
```
to
```
            <AppenderRef ref="Console" level="all"/>
            <AppenderRef ref="ApplicationLogger" level="all" />
```
3. Add the new `log4j2.xml`to the jar, run SPC again
