### ISSUE TITLE
[Improvement request]: JEI Tweaker should be removed from the list of clientside only mods

### ISSUE THREAD

**Issue by NevadaActual** [Griefed/ServerPackCreator#341]
### Whats the feature you would like to be improved?

JEI Tweaker is used for both visual AND mechanical recipes changes, and it's needed on the server to not cause errors with script loading.

### Anything else you would like to add?

It may have already been removed from the list at some point, and I'm just out of date? I didn't try to clean install the serverpack creator to see if the list updated, but if this Improvement/Feature request is no longer relevant the issue can be closed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya NevadaActual,

thanks for opening this improvement request.

I'll remove it with the next beta-release.
If you do not intend on using the beta, you will have to wait for a regular release. Once said release has happened, you can update the list from within the ServerPackCreator GUI:
Menu bar -> File -> Update Fallback Clientside Modslist

Then, when you create a new server pack configuration, the pre-filled list of clientside-only mods will have the latest entries, but without JEI Tweaker, as that will by then have been removed. 🙂
If you plan on continuing to use an old server pack configuration, you will have to remove the `JEITweaker` entry manually.

I distinctly remember JEITweaker causing problems when it was present on a server. I guess this was on older versions and I haven't checked since. Thanks for letting me know about this!

Cheers,
Griefed

**Comment by NevadaActual** [comment]
No problem! It might be the case that it causes issues in some cases, I have not looked into it at all, but I know that it's a required api for CraftTweaker to interface with JustEnoughItems in (at least) 1.16 and beyond. 

(Worst comes to worst, it's a problem whether or not it's included in serverpacks by default, and we'll have to let people know they need to test things before deploying like I didn't do. )

Thanks for the prompt response!
