### ISSUE TITLE
[Feature request]: Install Java if not found

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#437]
### Whats the feature you would like to be added?

Have the script automatically install the java required by the mod loader of the pack if java is not installed. Yes, a local copy just for the server.

### Anything else you would like to add?

You're doing great!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
I suggest you write a custom script template for this. It's what they are there for. 🙂

I do not have the time or interest in writing a system which covers the quadrillion different operating systems, their different distributions, architectures and versions to reliably install a working Java version.

Plus, this is really something a server admin has to take care of. I create server packs which users can run. The users/admins have to provide a system where said packs can run on.

On the same note. The 32-Bit detection is wonky in and of itself, too, because some Java JDKs don't even print their bitness when running the `version`-command.

Don't get me wrong, the idea is nice, but it is wayyyyyyy out of scope for me. It is simply impossible to anticipate the system a given user has and then install the corresponding Java version on said system. This would create more trouble for me than it would be worth. It's simply out of scope.

Cheers,
Griefed

**Comment by Griefed** [comment]
Additionally, if I were to take care of the installation of Java, I would then have to support all the different Java JDKs which end up on a given users system. Now THAT is something I can absolutely NOT do. 😂

**Comment by Griefed** [comment]
This answer may not be satisfactory to you, but it is one of the lines I have to draw at some point.

Cheers,
Griefed

**Comment by kreezxil** [comment]
Ouch, such sadness. the mention of the scripting template was sufficient.
Are things going well with you?

**Comment by Griefed** [comment]
Maybe the smilies didn't indicate the tone I intended this to come across with. Whoops :D I assure you, I was writing this in a good mood with with the intention of a slight chuckle. I was overemphasizing on purpose there. Guess that didn't work out too well! 🤣

I am good, thanks for asking. Really damn short on time due to finals coming up and not having a LegacyFabric modpack available to test the new LegacyFabric support in 3.13.0-beta.3, but oh well.

How're things on your end coming along?

**Comment by kreezxil** [comment]
Finally, fixed the quests in World of Dragons II after proving it to be
stable. Which opens the door for World of Dragons III: Be The Dragon that
will be built around Dragon Survival that allows players to become dragons
and is for 1.19.2 currently. This will be my first official dragon pack
that deviates away from Ice and Fire. I should have something available by
the end of the year. I'm in need of java coders to help me port my mods to
1.19.2 I've got three, but they all got "finals" or "life" or "both" in the
way. Looking for someone who is more like myself, available all the time
and would not mind an extra $20USD a week to port at least 1 mod each week
to 1.19.2 including cp share. Plus design new mods when all that is done
(about 38 mods in total). Easily a long term situational gig, and as I make
more money from the endeavor, so do they. You can verify that to be true,
as I've upped my stake in sponsoring you.

Thanks to your ongoing efforts, I very rarely use my manual methods. Much
applause to you my friend, and my goal by donating is to encourage you to
never quit, even after you land your dream job on Moon Base Alpha. :)

Speaking of the moon, don't you find it funny as hell that NASA insists on
doing their thing vs. contracting with Elon Musk. No, where is it mentioned
if Artemis will be reusable to such a nature that it can land itself
upright. It appears that it will do what the rockets of the 60s did and
break off in stages, dropping stuff into the already polluted oceans.

**Comment by kreezxil** [comment]
Profit doesn't necessarily imply greed. Elon treats his employees
exceedingly well in the paycheck and beyond. Shareholders too. I think it's
more of a case that the Biden Administration doesn't like Elon Musk. They
held an electric car symposium, invited everyone but Elon to it.

As per coders, I'm open to negotiations too. It can be a case by case basis
that way. Looking at a mod, deciding what needs to be done and having a bid
submitted.

**Comment by Griefed** [comment]
Everyone but him, eh? U.S of A...what are you doing 😅 *le sigh* 

Best of luck for the negotiations! If I had the time and knew anything about modding for Minecraft, I'd at least play with the idea, but as it stands, there's no chance I am getting into modding anytime soon.

**Comment by kreezxil** [comment]
Lol. I was mentioning it so that if you encounter someone willing to do it,
you could send them my way.

**Comment by Griefed** [comment]
Will do :)
