### ISSUE TITLE
MS5 [Feature request]: Switching profiles

### ISSUE THREAD

**Issue by TheButterbrotMan** [Griefed/ServerPackCreator#448]
### Whats the feature you would like to be added?

For different modpacks, you need different server.properties, icon.png, settings etc.

I would like to have profiles to switch between. I think that would be a really good improvement.

### Anything else you would like to add?

No.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya,

from your description I don't exactly get what the point of these proflles would be, how they should work (from the user perspective), and what benefit they would serve.

You can select a properties- and iconfile for each of your server packs individually already.

Cheers,
Griefed

**Comment by Griefed** [comment]
Heya TheButterbrotMan,

just poppin in to let you know that a rudimentary solution regarding this issue is available in the version 5 alpha. Both the server-icon and the server.properites now have a quick selection dropdown. Each of these have their corresponding directory in the server-files-directory in the home-directory of ServerPackCreator. Adding/removing files will automatically update those lists in the GUI, allowing you to add and remove files on the fly.

Anything else?

Cheers,
Griefed

**Comment by Griefed** [comment]
Heya TheButterbrotMan,

me again. Checking in to make sure nothing's missing here. Are there any other things you would be interested in being added, revolving around the feature discussed here?
If not, and if the already implemented features are to your satisfaction, I'll go ahead and close this issue. :)

Cheers,
Griefed

**Comment by Griefed** [comment]
A lack of feedback leads me to assume that everything is in order. I'll go ahead and close this issue, but feel free to reopen it or create a new issue if something comes up regarding this topic.

Cheers,
Griefed
