### ISSUE TITLE
[Improvement Ask]: Verification method

### ISSUE THREAD

**Issue by arthurbarret0** [Griefed/ServerPackCreator#498]
### Whats the improvement you would like to be made?

I've developed a Python script that analyzes the "mods.toml" file of all the mods in a directory, and with it, you can tell if the mod is clientside, serverside or bothside. It would be interesting to implement this detection method in ServerPackCreator.

See: https://raw.githubusercontent.com/reishosting/forge-modlist-analyzer/main/forge-modlist-analyzer.py

### Anything else you would like to add?

I tested the current tool with a modpack and it didn't work, incompatible mods remained on the server.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya arthurbarret0,

ServerPackCreator already has such a detection-system implemented which supports not only the Forge-way of doing things, as you are checking in your Python-script, but also the Fabric/Quilt way of declaring sideness.

If you believe to have an idea for an improvement of these mechanics, I'm all ears.
As of right now, unless I've overlooked something, your script wouldn't add anything new functionality-wise. Though having said script could be nice to server-admins who would like to modify already existing server packs.

Indeed, one improvement for your script would be to add cross-dependency checks, as in: Not only check the sideness of a mod, but also check whether it is a dependency for a server-side reqiured mod. SPC implemented this a couple of versions ago. Otherwise, you run the risk of removing a mod which itself is clientside, but is required by a server-side mod, thus creating a broken server pack, wich missing dependencies.

Cheers,
Griefed

**Comment by arthurbarret0** [comment]
Great, I really don't intend to move forward with the script. I plan to use ServerPackCreator (I didn't know about it when I developed my script).

I have a problem with ServerPackCreator, I tried using it with the modpack below, and it didn't work:
https://www.curseforge.com/minecraft/modpacks/primordio

I have some clients who want to use this modpack, I can even make it executable manually, but I would like something more practical, so that I can teach the clients more easily.

**Comment by Griefed** [comment]
If you encountered an error with ServerPackCreator, please open another issue, using the [Bug Report template](https://github.com/Griefed/ServerPackCreator/issues/new?assignees=Griefed&labels=bug&projects=&template=bug-report.yml&title=%5BBug%5D%3A+) and provide the `serverpackcreator.log` as well as any relevant modpack links, much like the one you posted already.

I'll try to reproduce the issue and see what I can do. :)
