### ISSUE TITLE
[Improvement Ask]: PLEASE do not remove previous server pack files when generating a new server pack under the same name. 

### ISSUE THREAD

**Issue by SivyxDev** [Griefed/ServerPackCreator#522]
### Whats the improvement you would like to be made?

When you create a server pack under the same name as a pack already in the directory, it SHOULD NOT completely overwrite that file and erase all data. It should instead act as an update to that pack, keeping all files that are not directly imported from the initial modpack. I have lost a world because of this, after updating my modpack. 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heyo,

I understand your frustration, but this behaviour is by design explicitly.
The tool is aimed at modpack developers. Thus, when they test a server pack, they must be absolutely certain that the generated one is clean of any previous files, without any remnants from previous generations running the risk of causing trouble.

It is not intended to manage or update local packs.
Server pack data gets changed by a modloader and mods all the time, so I wouldn't be able to check which one is *actually* the newer and 'correct' version.

Did you make a backup of your pack before you ran another generation over it?

Cheers Geiefed

**Comment by Griefed** [comment]
I'll see whether I can broaden the `Overwrite Server Pack` feature, maybe flesh it out a little.
No promises, though. The fact remains that modpack maintainers must be able to rely on the server pack always having the correct set of config, mods, etc.

**Comment by SivyxDev** [comment]
Hresponse.
 
I totally understand your reasoning for overwriting the original folder and I can definitely see that being the primary use case. I can say that I would enjoy a toggle (or maybe a separate "Update Pack" button) to make the software a little more friendly for personal server pack users. This instance of the issue was not detrimental to my server and I am glad I was able to figure that out before I accidentally deleted a lot more than I did. Thanks for your reaponse.

**Comment by Griefed** [comment]
Heyo, wanted to let you know that I've improved the `Server Pack Overwrites`-functionality a little.

Some more information at https://help.serverpackcreator.de/keeping-data.html

You can toggle it in the Global options in the settings screen.

**Comment by Griefed** [comment]
Check out https://help.serverpackcreator.de/keeping-data.html#updating-server-packs-experimental for details on how to test this feature. :)
