### ISSUE TITLE
[Improvement Ask]: Unnecessary server.jar download egress by force removal

### ISSUE THREAD

**Issue by AlexVialaBellander** [Griefed/ServerPackCreator#531]
### Whats the improvement you would like to be made?

If I have understood this correctly. For all Minecraft Versions larger than 1.16. the else [here](https://github.com/Griefed/ServerPackCreator/blob/5fbde6ccc4d11b707e781da48b6c65ee27c3565d/serverpackcreator-api/src/main/resources/de/griefed/resources/server_files/default_template.sh#L180) will execute, thus always leading to `rm -f server.jar` [here](https://github.com/Griefed/ServerPackCreator/blob/5fbde6ccc4d11b707e781da48b6c65ee27c3565d/serverpackcreator-api/src/main/resources/de/griefed/resources/server_files/default_template.sh#L199). This means that the `downloadIfNotExist` will always have to fetch the latest server.jar unnecessarily. 

Why do we do this? This will cause additional downloads from the site that could otherwise be skipped.

### Anything else you would like to add?

Well, ideally this wouldn't happen right? Why do we do it?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heyo AlexVialaBellander,

The same thing happens for NeoForge, too: https://github.com/Griefed/ServerPackCreator/blob/5fbde6ccc4d11b707e781da48b6c65ee27c3565d/serverpackcreator-api/src/main/resources/de/griefed/resources/server_files/default_template.sh#L232

And it also happens in the PowerShell scripts.
Here https://github.com/Griefed/ServerPackCreator/blob/5fbde6ccc4d11b707e781da48b6c65ee27c3565d/serverpackcreator-api/src/main/resources/de/griefed/resources/server_files/default_template.ps1#L338 and here https://github.com/Griefed/ServerPackCreator/blob/5fbde6ccc4d11b707e781da48b6c65ee27c3565d/serverpackcreator-api/src/main/resources/de/griefed/resources/server_files/default_template.ps1#L379

The reason for this was to always ensure people have the latest and greatest ServerStarterJar available to them, as NeoForges ServerStarterJar is quite awesome at handling both Forge and NeoForge. If a bug is fixed in the SSJ, then people would automatically receive a fixed version this way.

I could introduce a toggle to turn this on/off, with the default setting being on.

Thoughts?

Cheers,
Griefed

**Comment by AlexVialaBellander** [comment]
Hi Griefed,

Thank you for the expeditious reply and your contributions to the community. I believe making this configurable would be a great idea, and I hope you also recognise the potential benefits. At the same time, I understand the advantages of always fetching the latest version.

I have three proposals for how this could be implemented, with some arguments to aid your decision-making:

1. **Configure via `variables.txt`**  
   Add a `FORCE_FETCH` flag in the `variables.txt` file, similar to how other configurations are handled. This approach would make it easy for users to debug issues themselves and for the community to provide support if an update is required.

2. **Include an option in ServerPackCreator**  
   Implement an option directly within the ServerPackCreator application to ship the ZIP with the specified configuration. This provides flexibility, ensuring that all shipped versions are consistent. However, it might require more effort from users to update the client compared to simply adjusting the `variables.txt` file.

3. **A more complex but powerful solution**  
   An additional idea could be integrating a simple GET request to a REST API that checks for the latest version. If the local version doesn’t match the latest, it would trigger a fetch. You could adopt semantic versioning, where patch updates don’t necessitate an update, but minor or major ones do. This approach would require more planning, such as setting a standard for the API responses, so it might be overkill for now but worth considering in the long term.

**My recommendation**  
I suggest going with Option 1. It’s straightforward, fits with your existing methods, and allows server pack developers to set the default value while giving users the flexibility to change it. Another possibility is adding a flag to shell scripts like `sh start.sh --update`, which would force an update regardless of the config.

Thanks again for considering this!

**Comment by Griefed** [comment]
Heyo,

small update. I've decided to take the following approach:

1. Add a toggle for force fetching, configurable in the variables.txt, and also pre-configurable through the GUI
2. Add a version specifier to allow users to manually set the version, in case future version might no longer be compatible other otherwise unusable for a given user. If people want to always use the latest version, they'd have to set the fetch-toggle to `true` and the version to `latest`.

This will also be explained in the variables.txt comment section, so people can read up on it at their own leasure. :)

Cheers,
Griefed

**Comment by AlexVialaBellander** [comment]
Fantastic work. Many thanks for your contribution to the community ❤️
