### ISSUE TITLE
Excluded Folders (sub folders actually, but any should be allowed)

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#78]
* **What is the current behavior?**

Not able to exclude folders from server pack creation
* **What is the wanted/requested behavior?**

If I could exclude folders, i could avoid sending over the huge animation sequences found in the fancymenu and similar mods that provide client sided stuff. 
* **What are your reasons for making this feature request? Provide solid arguments on why I should start working on it.**
To be able to exclude files and folders from folders that are being included.

**Comment by Griefed** [comment]
Heya kreezxil,

thanks for opening a feature request.

So fancymenu stores everything inside `config/fancymenu/stuff`/morestuff` then? Good to know, that means I will never use it. 😅PackMenu stores it's things in `packmenu' *outside* the `config`-folder. I guess you could ask the creator of fancymenu to allow it's users to specify the path to resources.

How big are we talking when you say "huge animation sequences"? Is it actually worth the effort of working on an exclusion-feature? Because if it's just a couple of mb, then it#s not worth it. A couple of config-files are really not that huge. My pack has 357 files in it's `config-folder and it's just 1,15mb in size.

**Comment by kreezxil** [comment]
For me, on average about 150+ extra megabytes, I asked him a long time ago to move the folder to inside the config for easy exporting. So, it's probably a setting I'm ignoring. 

I don't want to ignore more stuff, i want to ignore the entire fancymenu, but it doesn't stop there, worldedit stores it's schematics in there, so i'd want to ignore that as well, even tho those can be useful on a server. there are quite a few client sided mods folders/files for conffigs i'd like to ignore their stuff. also this feature could be applied to the mods folder, some mods like to use the mods folder to cache things by making subfolders.

**Comment by Griefed** [comment]
150+mb?! Geesus!

I've got a similar functionality somewhere in SPC already, for creating server packs from a CurseForge modpack projectID;fileID-combination. I'll see about adding that for regular server packs. Configuration for exclusions will probably be available from the main menu and be stored in the serverpackcreator.properties, then.

**Comment by Griefed** [comment]
Will be available in the next alpha release. 🙂

**Comment by Griefed** [comment]
Available as of [3.0.0-alpha.6](https://github.com/Griefed/ServerPackCreator/releases/tag/3.0.0-alpha.6).
